### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by badfun** [dferber90/aws-cognito-next#3]
I get this error message, using both my own code and yours:

```
Server Error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```
I've gone through the React troubleshooting page [here ](https://reactjs.org/warnings/invalid-hook-call-warning.html) and not found any duplicates, etc. Seems to be something about the nested components is throwing it off. 

I tried to get a screen shot of the error but could not.
thanks.

**Comment by dferber90** [comment]
I would need more information to be able to help as this error can happen for many different reasons.

You can copy & paste the relevant parts of your code as a comment and format it using this icon:

![image](https://user-images.githubusercontent.com/1765075/85366537-d4fe2980-b527-11ea-8baf-2f55a03c8724.png)

**Comment by badfun** [comment]
Yes the error message is not terribly helpful. The relevant section of code that throws the error is:

`const Home = (props: { initialAuth: AuthTokens }) => {
  const auth = useAuth(props.initialAuth)
  const { login, logout } = useAuthFunctions()

  return (
    <React.Fragment>
      {auth ? (
        <button type="button" onClick={() => logout()}>
          sign out
        </button>
      ) : (
        <React.Fragment>
          <button type="button" onClick={() => login()}>
            sign in
          </button>
        </React.Fragment>
      )}
    </React.Fragment>
  )
}`

Here is the call stack:
`Call Stack
processChild
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/react-dom/cjs/react-dom-server.node.development.js (3043:14)
resolve
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/react-dom/cjs/react-dom-server.node.development.js (2960:5)
ReactDOMServerRenderer.render
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/react-dom/cjs/react-dom-server.node.development.js (3435:22)
ReactDOMServerRenderer.read
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/react-dom/cjs/react-dom-server.node.development.js (3373:29)
renderToString
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/react-dom/cjs/react-dom-server.node.development.js (3988:27)
render
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/next/dist/next-server/server/render.js (3:298)
Object.renderPage
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/next/dist/next-server/server/render.js (46:1020)
Function.getInitialProps
webpack:///pages/_document.tsx (92:33)
loadGetInitialProps
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/next/dist/next-server/lib/utils.js (5:101)
renderToHTML
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/next/dist/next-server/server/render.js (46:1330)
async
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/next/dist/next-server/server/next-server.js (68:285)
async
file:///C:/Users/Ken/Cloud/DEV/nextjs/cognito-auth/node_modules/next/dist/next-server/server/next-server.js (67:142)`

I'm new to Nextjs, so not sure yet what exactly is going on. But I will keep working on it and see what I can figure out. Any insight is appreciated.

**Comment by dferber90** [comment]
It looks like the error originates from the `getInitialProps` function in your `_document.tsx` file:

```
Function.getInitialProps
webpack:///pages/_document.tsx (92:33)
```

It seems you're trying to use hooks inside of `_document` which isn't supported afaik, see [docs](https://nextjs.org/docs/advanced-features/custom-document):

> React components outside of <Main /> will not be initialized by the browser. Do not add application logic here. If you need shared components in all your pages (like a menu or a toolbar), take a look at the App component instead

You can use a custom `App` component instead, see [here](https://nextjs.org/docs/advanced-features/custom-app).

Note that `aws-cognito-next` only requires a custom `App`, but not a custom `Document`, as shown in the [README](https://www.npmjs.com/package/aws-cognito-next#_apptsx).

Hope this helps.

**Comment by badfun** [comment]
Interesting. I don't have a `_document.tsx` file. According to the docs there is a default Document that you can override, but I have not done that. I just followed your Medium post and have the three files, `index.tsx`, `token.tsx`, and `_app.tsx` under `pages/`.

I get the same error when using your code cloned from the repository, so it must have something to do with my setup. I'll keep digging.
thanks for your help.

**Comment by dferber90** [comment]
Oh, then something might be up. The biggest difference I see is that you're using Windows and I'm on a Mac.

Did you install the dependencies using yarn or npm? I'd recommend yarn as that will use the `yarn.lock` file commited to the repo.

It could be that you end up with two different versions of React. That would explain why you are seeing the error message. So you could try deleting `node_modules` and then reinstalling the dependencies with yarn. If that doesn't work, then I'm out of ideas for now. Good luck!

**Comment by badfun** [comment]
Thanks. I use npm, it creates a lock file as well. I did try deleting the node_modules, and I also worked through the React troubleshooting page for that error and did not find any duplicates or such.

Oh well. I'll put this aside for now. Thanks for your help.
