### ISSUE TITLE
aws-amplify Next.js support

### ISSUE THREAD

**Issue by dferber90** [dferber90/aws-cognito-next#4]
aws-amplify will soon offer SSR support. Not sure yet what that will mean for this package.

https://github.com/aws-amplify/amplify-js/issues/5435

**Comment by ericclemmons** [comment]
Hey, this is a neat project!

The hooks and utilities look really helpful, so I don't think this project is replaced at all by that issue.

If anything, it'll mean less manual configuration in `Amplify.configure` and unblock more categories 👍
